resources:
  - ./namespace/namespace-vllm-inference.yaml
  - ./postgres/configmap-postgres.yaml
  - ./postgres/deployment-postgres.yaml
  - ./postgres/service-postgres.yaml
  - ./minio/configmap-minio.yaml
  - ./minio/pvc-minio.yaml
  - ./minio/deployment-minio.yaml
  - ./minio/service-minio.yaml
  - ./minio/route-minio.yaml
  - ./chat-ui/configmap-chat-ui.yaml
  - ./chat-ui/deployment-chat-ui.yaml
  - ./chat-ui/service-chat-ui.yaml
  - ./chat-ui/route-chat-ui.yaml
  - ./image-service/configmap-image-service.yaml
  - ./image-service/pvc-image-service.yaml
  - ./image-service/deployment-image-service.yaml
  - ./image-service/service-image-service.yaml
  - ./image-service/route-image-service.yaml