FROM quay.io/fedora/python-312-minimal:latest

WORKDIR /app

# RUN microdnf -y install git libpq python3 && microdnf clean all

COPY main.py .
COPY requirements.txt .

RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8100
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8100"]
