FROM registry.redhat.io/rhaiis/vllm-cuda-rhel9:3.3.0

WORKDIR /app

# RUN microdnf -y install git libpq python3 && microdnf clean all

COPY main.py .
COPY requirements.txt .

RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

EXPOSE 8100
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8100"]
