apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-service-model-cache
  labels:
    app: image-service
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
